<?php
// Constantes de produccion

return [
	"TAREA_ARMADO" => "30",
	"TAREA_EMPAQUE" => "34",
	"TAREA_PENDIENTE_FABRICACION" => "31",
	"TAREA_CORTADO_DE_FORRO" => "14",
	"TAREA_TERMINADA" => "32",
	"TAREA_FACTURADA" => "33",
	"TAREA_TERMINADA_STOCK" => "39",
	"TAREA_ESTADO_PRODUCCION" => "P",
	"TAREA_ESTADO_TERMINADA" => "T",
	"TAREA_ESTADO_FACTURADA" => "F",
	"EMPLEADO_FERLI" => "33",
	"EMPLEADO_FABRICA" => "48",
	"OPERACION_INICIO" => "1",
	"OPERACION_FIN" => "2",
	"DESDE_MEDIDA" => "21",
	"HASTA_MEDIDA" => "47",
	"DESDE_INTERVALO1" => "16",
	"HASTA_INTERVALO1" => "26",
	"DESDE_INTERVALO2" => "27",
	"HASTA_INTERVALO2" => "33",
	"DESDE_INTERVALO3" => "34",
	"HASTA_INTERVALO3" => "40",
	"DESDE_INTERVALO4" => "41",
	"HASTA_INTERVALO4" => "47",
	"HASTA_MEDIDA_CHICO" => "35",
	"DESDE_MEDIDA_TOMAHAWK" => "5",
	"CLIENTE_STOCK" => "620",
	"NOMBRE_CLIENTE_STOCK" => "STOCK",
	"TIPOTRANSACCION_CONSUME_OT" => "4",
	"TIPOTRANSACCION_ALTA_PRODUCCION" => "3",
	"SECUENCIA_TAREAS" => [
							'30' => ['1', '6'],
							'34' => ['30'],
							'33' => ['34', '32', '39'],
							'32' => ['34']
						]
	];

