<?php
// Constantes de produccion

return [
	"TAREA_ARMADO" => "30",
	"TAREA_EMPAQUE" => "34",
	"TAREA_PENDIENTE_FABRICACION" => "31",
	"TAREA_TERMINADA" => "32",
	"TAREA_FACTURADA" => "33",
	"TAREA_ESTADO_TERMINADA" => "T",
	"TAREA_ESTADO_FACTURADA" => "F",
	"DESDE_MEDIDA" => "21",
	"HASTA_MEDIDA" => "47",
	"DESDE_INTERVALO1" => "16",
	"HASTA_INTERVALO1" => "26",
	"DESDE_INTERVALO2" => "27",
	"HASTA_INTERVALO2" => "33",
	"DESDE_INTERVALO3" => "34",
	"HASTA_INTERVALO3" => "40",
	"DESDE_INTERVALO4" => "41",
	"HASTA_INTERVALO4" => "47",
	"HASTA_MEDIDA_CHICO" => "35",
	"CLIENTE_STOCK" => "620",
	"TIPOTRANSACCION_CONSUME_OT" => "4",
	"TIPOTRANSACCION_ALTA_PRODUCCION" => "3"
		];

